// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRvssPH_lsiDDkK0chMP5pS8TbYAQfPAc',
    appId: '1:405827173181:web:172d2dc5b75f827b2f6354',
    messagingSenderId: '405827173181',
    projectId: 'wheelstrade-11db7',
    authDomain: 'wheelstrade-11db7.firebaseapp.com',
    storageBucket: 'wheelstrade-11db7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3rD3UdydbFfrrW7ad-PzrNRdSWblNeC4',
    appId: '1:405827173181:android:54baf11ceab5b6a12f6354',
    messagingSenderId: '405827173181',
    projectId: 'wheelstrade-11db7',
    storageBucket: 'wheelstrade-11db7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqnaZ3oBV_o5Zcj-fZRXpkuMyWczzrbWE',
    appId: '1:405827173181:ios:e83d4854fee9890e2f6354',
    messagingSenderId: '405827173181',
    projectId: 'wheelstrade-11db7',
    storageBucket: 'wheelstrade-11db7.appspot.com',
    iosBundleId: 'com.example.wheelsTrade',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqnaZ3oBV_o5Zcj-fZRXpkuMyWczzrbWE',
    appId: '1:405827173181:ios:e83d4854fee9890e2f6354',
    messagingSenderId: '405827173181',
    projectId: 'wheelstrade-11db7',
    storageBucket: 'wheelstrade-11db7.appspot.com',
    iosBundleId: 'com.example.wheelsTrade',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRvssPH_lsiDDkK0chMP5pS8TbYAQfPAc',
    appId: '1:405827173181:web:635931c23b3e02c22f6354',
    messagingSenderId: '405827173181',
    projectId: 'wheelstrade-11db7',
    authDomain: 'wheelstrade-11db7.firebaseapp.com',
    storageBucket: 'wheelstrade-11db7.appspot.com',
  );
}
